main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('art/', views.ArtList.as_view(), name='art_index'),
    path('art/create/', views.ArtCreate.as_view(), name='art_create'),
    path('profile/create/', views.ProfileCreate.as_view(), name='profile_create'),
    path('profile/<int:user_id>/', views.profile_detail, name='profile_detail'),
    path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name='profile_update'),
    path('art/<int:pk>/', views.ArtDetail.as_view(), name='art_detail'),
    path('art/<int:pk>/update/', views.ArtUpdate.as_view(), name='art_update'),
    path('art/<int:pk>/delete/', views.ArtDelete.as_view(), name='art_delete'),
    path('gallery/', views.gallery_index, name='gallery_index'),
    path('gallery/<int:art_id>/', views.gallery_detail, name='gallery_detail'),
    path('art/<int:art_id>/add_comment/', views.add_comment, name='add_comment'),
    path('gallery/<int:art_id>/comment/<int:pk>/update/', views.CommentUpdate.as_view(), name="comment_update"),
    path('gallery/<int:art_id>/comment/<int:pk>/delete/', views.CommentDelete.as_view(), name="comment_delete"),
    path('paint/', views.paint, name='paint'),
    path('files/', views.files, name='files'),
    path('codepen/', views.codepen, name='codepen'),
    path('harvardartapi/', views.harvard_art_api, name="harvard_art_api")
]

pycasso/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

main_app/models.py
import datetime
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# tags see https://django-tagging.readthedocs.io/en/develop/
# Create your models here.

MEDIA_TYPES = (
    ('C', 'Camera Photography'),
    ('D', 'Digital Artwork'),
    ('J', 'CSS codepen'),
    ('P', 'Painting'),
    ('S', 'Sketch Drawing'),
)

ARTIST_TYPES = (
    ('1', ('Photographer')),
    ('2', ('Painter')),
    ('3', ('Digital Illustrator')),
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500)
    birthday = models.DateField(default='2020-09-17')
    artist_type = models.CharField(max_length=25, choices=ARTIST_TYPES, default=MEDIA_TYPES[0][0])
    is_public = models.BooleanField(default=True)
    location = models.CharField(max_length=100)
    profile_img = models.CharField(max_length=100)
    points = models.IntegerField(default=1)

    def get_absolute_url(self):
        return reverse ('profile_detail', kwargs={'user_id': self.user.id})

class Art(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    media_type = models.CharField(max_length=1, choices=MEDIA_TYPES)
    genre = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    colors_used = models.TextField(max_length=250)
    karma = models.IntegerField(default=1)
    date_posted = models.DateField()
    is_public = models.BooleanField(default=True)
    url = models.CharField(max_length=200)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('art_index')

class Comment(models.Model):
    comment = models.TextField(max_length=500)
    rating = models.IntegerField()
    date_created = models.DateField()
    art = models.ForeignKey(Art, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('gallery_detail', kwargs={ 'art_id': self.art.id })




class PaintFile(models.Model):
    name = models.CharField(max_length=30)
    image = models.TextField()
    canvas_image = models.TextField()

    def __unicode__(self):
        return self.name

main_app/forms.py
from .models import Comment, Art
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', 'rating', 'date_created')

main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid
import boto3
import json
import requests
from decouple import config

from .models import Art, Profile, Comment, PaintFile
from .forms import CommentForm
from . import services


S3_BASE_URL = config('S3_BASE_URL')
BUCKET = config('BUCKET')
HARVARD_ART_URL = config('HARVARD_ART_URL')
HARVARD_API_KEY = config('HARVARD_API_KEY')


# Create your views here.


def home(request):
    return render(request, 'home.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = Profile()
            user_profile.user = user
            user_profile.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up, please try again.'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


@csrf_exempt
def paint(request):
    if request.method == 'GET':
        return render(request, 'paint.html')
    elif request.method == 'POST':
        filename = request.POST.get('save_fname')
        data = request.POST.get('save_cdata')
        image = request.POST.get('save_image')
        file_data = PaintFile(name=filename, image=data, canvas_image=image)
        file_data.save()
        return redirect('home')

@csrf_exempt
def files(request):
    if request.method == 'GET':
        all_data = PaintFile.objects.all()
        return render(request, "files.html", {'files': all_data})

def codepen(request):
    return render(request, 'codepen/codepen.html')

def harvard_art_api(request):
    if request.method =='POST':
        title = request.POST['title']
        art_list = services.get_art_data(title)
        return render(request, 'harvard_art_api/harvard_art_api.html', art_list)
    return render(request, 'harvard_art_api/harvard_art_api.html')

class ArtList(LoginRequiredMixin, ListView):
    model = Art
    
    def get_queryset(self):
        return Art.objects.filter(user=self.request.user)

class ArtCreate(LoginRequiredMixin, CreateView):
    model = Art
    fields = ['title', 'media_type', 'genre', 'description', 'colors_used', 'karma', 'date_posted', 'is_public']
              
    def form_valid(self, form):
        art_file = self.request.FILES.get('art-file', None)
        if art_file:
            s3 = boto3.client('s3')
            key = uuid.uuid4().hex[:6] + \
                art_file.name[art_file.name.rfind('.'):]
            try:
                s3.upload_fileobj(art_file, BUCKET, key)
                url = f'{S3_BASE_URL}{BUCKET}/{key}'
                form.instance.url = url
            except:
                print('An error ocurred uploading the file to s3.')
        form.instance.user = self.request.user
        return super().form_valid(form)

class ArtDetail(LoginRequiredMixin, DetailView):
    model = Art

class ArtUpdate(LoginRequiredMixin, UpdateView):
    model = Art
    fields = ['title', 'media_type', 'genre', 'description', 'colors_used', 'karma', 'date_posted', 'is_public']


    def form_valid(self, form):
        art_file = self.request.FILES.get('art-file', None)
        if art_file:
            s3 = boto3.client('s3')
            key = uuid.uuid4().hex[:6] + art_file.name[art_file.name.rfind('.'):]
            try:
                s3.upload_fileobj(art_file, BUCKET, key)
                url = f'{S3_BASE_URL}{BUCKET}/{key}'
                form.instance.url = url
            except:
                print('An error occurred uploading the file to s3.')
        form.instance.user = self.request.user
        return super().form_valid(form)

class ArtDelete(LoginRequiredMixin, DeleteView):
    model = Art
    success_url = '/art/'

def gallery_index(request):
    art = Art.objects.all()
    return render(request, 'gallery/gallery_index.html', { 'art': art })

def gallery_detail(request, art_id):
    art = Art.objects.get(id=art_id)
    comment_form = CommentForm()
    return render(request, 'gallery/gallery_detail.html', { 'art': art, 'comment_form': comment_form })

@login_required
def add_comment(request, art_id):
    form = CommentForm(request.POST)

    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.art_id = art_id
        new_comment.user = request.user
        new_comment.save()
    return redirect('gallery_detail', art_id=art_id)

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ['comment', 'rating', 'date_created']
    
class CommentDelete(LoginRequiredMixin, DeleteView):
    model = Comment
    success_url = '/gallery/'
        
class ProfileCreate(LoginRequiredMixin, CreateView):
    model = Profile
    fields = ['bio', 'birthday', 'artist_type', 'is_public', 'location', 'points']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['bio', 'birthday', 'artist_type', 'is_public', 'location', 'points']

    def form_valid(self, form):
        img_file = self.request.FILES.get('profile-img', None)
        if img_file:
            s3 = boto3.client('s3')
            key = uuid.uuid4().hex[:6] + img_file.name[img_file.name.rfind('.'):]
            try:
                s3.upload_fileobj(img_file, BUCKET, key)
                url = f'{S3_BASE_URL}{BUCKET}/{key}'
                form.instance.profile_img = url
            except:
                print('An error ocurred uploading the file to s3.')
        return super().form_valid(form)

def profile_detail(request, user_id):
    profile = Profile.objects.get(user=user_id)
    print(profile)
    return render(request, 'profile/detail.html', { 'profile': profile })

main_app/templates/main_app/art_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete Art</h1>

<h4>Are you sure you want to delete {{ object.name }}?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Delete!" />
  <a href="{% url 'art_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/art_detail.html
{% extends 'base.html' %}
{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js"
    integrity="sha512-HzAEuXwhLxwm/Jj+5ecdjzrRVrjuh2ZeIxyT1Ln37TO5pWNMnKBuU7cfd1wvRQ/k86w1oC174Yk1T7aRlBpIcA=="
    crossorigin="anonymous"></script>


<section class="art-img-section">
    <div class="art-img">
        <img src="{{ object.url }}" alt="">
    </div>
    <div class="art-page-detail">
        <div>
            <h3>{{ object.title }}</h3>
        </div>
        <div>
            <h4>Media type: {{ object.get_media_type_display }}</h4>
            <h4>Genre: {{ object.genre }}</h4>
            <p>Description: {{ object.description }}</p>
            <p>Date Posted: {{ object.date_posted }} </p>
            <h4>Colors used: {{object.colors_used}}</h4>
            <h4>Karma: {{ object.karma }}</h4>
            <a href="{% url 'art_update' object.id %}">Update Art</a>
            <a href="{% url 'art_delete' object.id %}">Delete Art</a>
        </div>
    </div>
</section>

<script>
    function splitScroll() {
        const controller = new ScrollMagic.Controller();

        new ScrollMagic.Scene({
                duration: '100%',
                triggerElement: '.art-page-detail',
                triggerHook: 0
            })
            .setPin('.art-img')
            .addTo(controller);
    }

    splitScroll();
</script>

{% endblock %}

main_app/templates/main_app/art_form.html
{% extends 'base.html' %}


{% block content %}
{% if object %}

<h1>Edit {{ object.name }}</h1>
{% else %}
<h1> Add Artwork </h1>
{% endif %}
<form action='' class="art-form-wrapper" enctype='multipart/form-data' method='POST'>
    <div class="add-art-div justify-center-ns">
        {% csrf_token %}
        <table class="add-form">
            {{ form.as_table }}
        </table>
        <br><br>
        <input type='file' name='art-file' value='{{ object.url }}'>
        <br><br>
        <input type='submit' class="add-button" value='Add Art'>
        <a class="add-form-a" href="{% url 'art_index' %}">Cancel</a>
    </div>
</form>

<script>
    $(function () {
        $("#id_date_posted").datepicker();
    });
</script>


{% endblock %}

main_app/templates/main_app/art_list.html
{% extends 'base.html' %}

{% block content %}

<article class="cf">
    {% for object in object_list %}    
        <div class="fl w-50 w-25-ns" id="div">
            <a href="{% url 'art_detail' object.id %}" class="db aspect-ratio aspect-ratio--1x1 ">
                <span role="img" style="background-image:url({{object.url}});" class="bg-center cover aspect-ratio--object "></span>               
            </a>   
        </div>
    {% empty %}
    <h3>No Art to display yet...</h3>
    {% endfor %}
  
</article>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
   var random = Math.floor((Math.random() * 5)  + 1)
$(`#div:nth-child(${random}n)`).attr("class", "fl w-50");        
</script>
{% endblock %}

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Comment</h1>

<h4>Are you sure you want to delete your comment?</h4>
<p>{{ object.comment }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete!">
    <a href="{% url 'gallery_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/comment_form.html
{% extends 'base.html' %}

{% block content %}
<form action="" class="art-form-wrapper" method="POST">
    <div class="add-art-div justify-center-ns">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <br><br>
    <input type="submit" value="Update Comment">
    <a href="{% url 'gallery_detail' object.art.id %}">Cancel</a>
</div>
</form>

<script>
    $(function () {
        $("#id_date_created").datepicker();
    });
</script>


{% endblock %}

main_app/templates/main_app/profile_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Edit<span class="teal-text">{{ object.name }}</span></h1>
{% else %}
<h1>Profile</h1>
{% endif %}

<form action="" class="art-form-wrapper" enctype="multipart/form-data" method="post">
    <div class="add-art-div justify-center-ns">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input class="btn" type="submit" value="Submit!">
        <input type="file" name="profile-img" value="{{ object.profile_img }}">
    </div>
</form>

<script>
    $(function () {
        $("#id_birthday").datepicker();
    });
</script>

{% endblock %}